### ISSUE TITLE
GCC toolchain (<= 4.8) doesn't enable optimizations for X64 RELEASE builds

### ISSUE THREAD

**Issue by bcran** [tianocore/edk2#34]
There are a few places `-Os` is present in tools_def.txt, but none for X64 RELEASE GCC on the UDK2014.SP1 branch. Since the MSFT toolchains _do_ have optimizations enabled in release builds, it seems this is a bug.

**Comment by mytbk** [comment]
I used -Os in tools_def.txt before, but gcc fails to build because -Os has some conflicts with (ms_abi), so there's no -Os for gcc.

**Comment by bcran** [comment]
I'm using -Os successfully with gcc 4.9 at least.

**Comment by lersek** [comment]
gcc-4.8 accepts `-Os` if `-maccumulate-outgoing-args` is specified in addition, but unfortunately it also misbuilds edk2 that way. Sergey Isakov reported however that gcc-4.9 worked for him, so that seems consistent with @bcran's comment https://github.com/tianocore/edk2/issues/34#issuecomment-163924630. See this thread:

http://thread.gmane.org/gmane.comp.bios.tianocore.devel/10963

This is quite unfortunate, because `-Os` brings significant space savings.

**Comment by lersek** [comment]
@bcran since this appears to apply to edk2 master as well, I propose to remove the UDK reference from the title. Thanks.

**Comment by bcran** [comment]
@lersek I added the UDK reference to indicate that it wasn't a new bug - because it might be nice to have fixes committed to other branches such as UDK2014.SP1 and UDK2015 in addition to master.

**Comment by lersek** [comment]
@bcran point taken, setting tags.
