### ISSUE TITLE
 RamDiskDxe: removal action doesn't do anything when 9 disks exist

### ISSUE THREAD

**Issue by bcran** [tianocore/edk2#81]
If a user creates 9 raw RAM Disks using the default size of 0x1000, then at some point some of them become selected ("[X]") in the list automatically. 

Furthermore, the "Remove selected RAM disk(s)." option appears to have no effect anymore - none of the disks are deleted. 

Pressing ESC to leave the screen causes a "Changes have not been saved. Save Changes and exit?" dialog to appear. Pressing 'Y' has no effect.

**Comment by bcran** [comment]
Label issue as OVMF.

**Comment by lersek** [comment]
Hm, I don't think it is right to label this as OVMF. OvmfPkg does not provide any code related specifically to RAM Disks. I think it would be more appropirate to attribute this to RamDiskDxe, since the exact string that you quote ("Remove selected RAM disk(s)") can be found in `MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskHiiStrings.uni`.

**Comment by hwu25** [comment]
It is a bug for the RamDiskDxe driver in the MdeModulePkg. I will send out  a patch to fix this issue later.

**Comment by lersek** [comment]
Patch on list:
http://thread.gmane.org/gmane.comp.bios.edk2.devel/10968

**Comment by hwu25** [comment]
The issue is fixed by commit 09abc636756b5d1f29224402181f7fd34f736c5f.
@lersek Could you help to close this issue?

**Comment by lersek** [comment]
@hwu25: closing.

But, as a tianocore group member, I think you should also be able to close edk2 project issues. @jljusten, any thoughts? Thanks.
