### ISSUE TITLE
UefiCpuPkg: MtrrLib: unused-but-set-variable (UDK2015 branch)

### ISSUE THREAD

**Issue by bcran** [tianocore/edk2#98]
With gcc 6.1.1, a DEBUG build of OVMF from the UDK2015 branch fails:

./OvmfPkg/build.sh -a X64 -t GCC49 -b DEBUG

/home/bcran/workspace/edk2/UefiCpuPkg/Library/MtrrLib/MtrrLib.c: In function ‘ProgramFixedMtrr’:
/home/bcran/workspace/edk2/UefiCpuPkg/Library/MtrrLib/MtrrLib.c:462:11: error: variable ‘TempQword’ set but not used [-Werror=unused-but-set-variable]
   UINT64  TempQword;
           ^~~~~~~~~
cc1: all warnings being treated as errors
make: **\* [GNUmakefile:299: /home/bcran/workspace/edk2/Build/OvmfX64/DEBUG_GCC49/X64/UefiCpuPkg/Library/MtrrLib/MtrrLib/OUTPUT/MtrrLib.obj] Error 1

**Comment by lersek** [comment]
Hi Bruce,

on the master branch, this issue has been fixed by commit 16e93125b506e30e53f63be4af0255a3afb0210b (part of a larger series).

I'm unsure what the UDK2015 cherry-picking policy is (considering especially that we don't (yet?) support OvmfPkg outside of the master branch) , but for now I'll move this report to UefiCpuPkg where it belongs.

**Comment by lgao4** [comment]
We will sync it to UDK2015 branch.
